#!/usr/bin/env python3

from pathlib import Path
import os
import sys
import argparse
import shutil
import tempfile


# ============================================================
# Paths
# ============================================================

# scripts/gen_env.py
SCRIPT_DIR = Path(__file__).resolve().parent

# Racine du projet
PROJECT_ROOT = SCRIPT_DIR.parent

# Fichier .env à la racine
ENV_FILE = PROJECT_ROOT / ".env"


# ============================================================
# Environment
# ============================================================

ENV_VALUES = {
    "GTAV": "https://raw.githubusercontent.com/alloc8or/gta5-nativedb-data/master/natives.json",
    "GTAVEE": "https://raw.githubusercontent.com/alloc8or/gta5-nativedb-data/master/natives_gen9.json",
    "RDR2": "https://raw.githubusercontent.com/alloc8or/rdr3-nativedb-data/master/natives.json",
    "RDR": "https://cdn.veyvy.space/data/scdb/rdr.h",
    "MP3": "https://cdn.veyvy.space/data/scdb/mp3.h",
    "GTAIV": "https://cdn.veyvy.space/data/scdb/gtaIV.h",

    "DISCORD_BOT_URL": (
        "https://discord.com/oauth2/authorize?"
        "client_id=1428793215938592809"
        "&permissions=8"
        "&integration_type=0"
        "&scope=bot+applications.commands"
    ),

    "DISCORD_SERVER_URL": "https://discord.gg/cyNP2bn9xE",
}


# ============================================================
# Console
# ============================================================

def info(message: str):
    print(f"[INFO] {message}")


def success(message: str):
    print(f"[OK]   {message}")


def warning(message: str):
    print(f"[WARN] {message}")


def error(message: str):
    print(f"[ERR]  {message}")


# ============================================================
# .env generation
# ============================================================

def quote_env_value(value: str) -> str:
    """
    Entoure les valeurs de guillemets pour éviter les problèmes
    avec &, ?, =, etc.
    """

    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    value = value.replace("\n", "\\n")
    value = value.replace("\r", "\\r")

    return f'"{value}"'


def generate_env() -> str:
    """
    Génère le contenu du fichier .env.
    """

    lines = [
        "# ============================================================",
        "# AUTO-GENERATED FILE",
        "# Generated by scripts/gen_env.py",
        "# ============================================================",
        "",
        "# GTA / Rockstar Native Databases",
        "",
    ]

    for key in (
        "GTAV",
        "GTAVEE",
        "RDR2",
        "RDR",
        "MP3",
        "GTAIV",
    ):
        lines.append(
            f"{key}={quote_env_value(ENV_VALUES[key])}"
        )

    lines.extend(
        [
            "",
            "# Discord",
            "",
            (
                "DISCORD_BOT_URL="
                f"{quote_env_value(ENV_VALUES['DISCORD_BOT_URL'])}"
            ),
            (
                "DISCORD_SERVER_URL="
                f"{quote_env_value(ENV_VALUES['DISCORD_SERVER_URL'])}"
            ),
            "",
        ]
    )

    return "\n".join(lines)


# ============================================================
# Backup
# ============================================================

def create_backup() -> Path | None:
    """
    Sauvegarde le .env actuel avant remplacement.
    """

    if not ENV_FILE.exists():
        return None

    backup = PROJECT_ROOT / ".env.backup"

    index = 1

    while backup.exists():
        backup = PROJECT_ROOT / f".env.backup.{index}"
        index += 1

    shutil.copy2(ENV_FILE, backup)

    return backup


# ============================================================
# Atomic write
# ============================================================

def write_env(content: str):
    """
    Écrit le fichier temporairement puis le remplace.
    """

    fd, temp_path = tempfile.mkstemp(
        prefix=".env.",
        dir=PROJECT_ROOT,
        text=True,
    )

    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            file.write(content)

        os.replace(temp_path, ENV_FILE)

    except Exception:
        try:
            os.unlink(temp_path)
        except OSError:
            pass

        raise


# ============================================================
# Permissions
# ============================================================

def secure_env():
    """
    Sur Linux/macOS, limite les permissions du .env.
    """

    if os.name != "nt":
        try:
            ENV_FILE.chmod(0o600)
        except OSError as exc:
            warning(
                f"Impossible de modifier les permissions : {exc}"
            )


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate the project's .env file."
    )

    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Overwrite existing .env",
    )

    parser.add_argument(
        "--backup",
        "-b",
        action="store_true",
        help="Backup existing .env before overwriting",
    )

    return parser.parse_args()


# ============================================================
# Main
# ============================================================

def main() -> int:
    args = parse_args()

    print()
    print("=" * 60)
    print("              ENVIRONMENT GENERATOR")
    print("=" * 60)
    print()

    info(f"Script       : {Path(__file__).resolve()}")
    info(f"Project root : {PROJECT_ROOT}")
    info(f"Output       : {ENV_FILE}")
    print()

    # --------------------------------------------------------
    # Existing .env
    # --------------------------------------------------------

    if ENV_FILE.exists() and not args.force:
        error(".env already exists.")
        print()
        print("Use:")
        print("  python scripts/gen_env.py --force")
        print()
        print("Or with backup:")
        print("  python scripts/gen_env.py --force --backup")
        print()

        return 1

    # --------------------------------------------------------
    # Backup
    # --------------------------------------------------------

    if ENV_FILE.exists() and args.backup:
        try:
            backup = create_backup()

            if backup:
                success(f"Backup created: {backup}")

        except OSError as exc:
            error(f"Backup failed: {exc}")
            return 1

    # --------------------------------------------------------
    # Generate
    # --------------------------------------------------------

    try:
        content = generate_env()
        write_env(content)
        secure_env()

    except OSError as exc:
        error(f"Unable to generate .env: {exc}")
        return 1

    # --------------------------------------------------------
    # Result
    # --------------------------------------------------------

    print()
    success("Environment file generated successfully!")
    print()

    print("Variables:")
    for key in ENV_VALUES:
        print(f"  ✓ {key}")

    print()
    info(f"File: {ENV_FILE}")

    return 0


if __name__ == "__main__":
    sys.exit(main())